In [1]:
import pandas as pd
import re

In [2]:
lines = pd.read_csv("fixed_lines.csv")

In [3]:
lines.dialogue = lines.dialogue.str.upper()

In [4]:
lines

,lineId,chId,mId,chName,dialogue
0,L1045,u0,m0,BIANCA,THEY DO NOT!
1,L1044,u2,m0,CAMERON,THEY DO TO!
2,L985,u0,m0,BIANCA,I HOPE SO.
3,L984,u2,m0,CAMERON,SHE OKAY?
4,L925,u0,m0,BIANCA,LET'S GO.
...,...,...,...,...,...
293197,L666371,u9030,m616,DURNFORD,LORD CHELMSFORD SEEMS TO WANT ME TO STAY BACK ...
293198,L666370,u9034,m616,VEREKER,I'M TO TAKE THE SIKALI WITH THE MAIN COLUMN TO...
293199,L666369,u9030,m616,DURNFORD,YOUR ORDERS MR VEREKER?
293200,L666257,u9030,m616,DURNFORD,GOOD ONES YES MR VEREKER. GENTLEMEN WHO CAN RI...
293201,L666256,u9034,m616,VEREKER,COLONEL DURNFORD... WILLIAM VEREKER. I HEAR YO...